name: dart_skills
description: A web app showcasing Dart skills.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  js: ^0.6.7
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
  build_web_compilers: ^4.0.0
  build_web_compilers: ^4.0.0
  test: ^1.16.0
